env:
  global:
    - secure: UP0F0/tspgDnPsxZ4uCdRUcfhBrmHKtdWZ7fhGuTq4rHBeC9CxwqVB//JKEr0XTqzDHhQ2J53S7j7XY90h9P+9kQoTmkuOxLs1FNYXg011/rVkwEwu0427M+Oye2CbENWgaf4OycPgkbZR2USKwKg53oGniAyyz6/xm8IlAZRng=

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      dist: bionic
      language: python
      python: 3.6
      env: PYTHON=python PIP=pip
      cache: pip
    - os: linux
      sudo: required
      dist: xenial
      language: python
      python: 3.6
      env: PYTHON=python PIP=pip
      cache: pip
    - os: osx
      osx_image: xcode10.1
      env: PYTHON=python3 PIP=pip3
      cache: "$HOME/Library/Caches/pip"
    - os: osx
      osx_image: xcode11
      env: PYTHON=python3 PIP=pip3
      cache: "$HOME/Library/Caches/pip"

addons:
  apt:
    packages:
      - libusb-1.0
      - libboost-all-dev
  coverity_scan:
    project:
      name: analogdevicesinc/libsmu
      description: Software abstractions for the analog signal exploration tools (ADALM1000)
    notification_email: alexandra.trifan@analog.com
    build_command_prepend: mkdir -p build && cd build && cmake -DBUILD_PYTHON=OFF ..
    build_command: make
    branch_pattern: coverity_scan

# build from all branches except appveyor (windows builds)
branches:
  except:
    - appveyor
before_install:
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew update; fi

install:
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew install libusb; fi
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew install ${PYTHON} || true; fi
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew upgrade cmake || true; fi

  # for python bindings
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then sudo easy_install pip; fi
  - ${PIP} install --only-binary ":all:" --disable-pip-version-check --upgrade pip
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then sudo ${PIP} install --only-binary ":all:" wheel cython ; fi
  - if [[ ${TRAVIS_OS_NAME} == linux ]]; then ${PIP} install --only-binary ":all:" wheel cython ; fi

script:
  # build tar containg python files
  - if [[ ${TRAVIS_OS_NAME} == linux ]]; then mkdir -p build_tar && cd build_tar; fi
  - if [[ ${TRAVIS_OS_NAME} == linux ]]; then cmake -DDEB_DETECT_DEPENDENCIES=ON -DENABLE_PACKAGING=ON -DUSE_PYTHON2=OFF -DBUILD_PYTHON=ON ..; make package; rm *.deb; cd .. ; fi

  - mkdir -p build && cd build
  - if [[ ${TRAVIS_OS_NAME} == linux ]]; then cmake -DDEB_DETECT_DEPENDENCIES=ON -DENABLE_PACKAGING=ON -DUSE_PYTHON2=OFF -DBUILD_PYTHON=OFF ..; make package; rm *.tar.gz; fi

  # Build tar.gz for OSX (contains libraries and python bindings)
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then cmake -DENABLE_PACKAGING=ON -DUSE_PYTHON2=OFF ..; make package; fi

  # Build pkg for OSX (contains libsmu.framework - only base library)
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then cmake -DOSX_PACKAGE=ON -DENABLE_PACKAGING=OFF -DUSE_PYTHON2=OFF .. ; fi
  - make
  - ls

  - cd "${TRAVIS_BUILD_DIR}"/bindings/python
  - "${PYTHON} --version"
  - ${PYTHON} -c "import struct; print(struct.calcsize('P') * 8)"
  - ${PYTHON} setup.py build_ext -L "${TRAVIS_BUILD_DIR}"/build/src
  - "${PYTHON} setup.py build"
  - "${PYTHON} setup.py bdist_wheel --skip-build"

before_deploy:
  - ". ${TRAVIS_BUILD_DIR}/CI/travis/before_deploy"


deploy:
  - provider: releases
    api_key:
      secure: S78x4D4rzTWi3zI19dafohAplHDfyeDyzRYVz0WXf+g7WHKXa+aWPjsKyfrt8xwdkQoinzn1EwUUWjIZgpyD5gHUetdKqS5UroYOe/ZMBoT260PJ6QuZrTbg98EmDtjNrcLYHCldj2bvpoUV1gJozo32WiCND8VBttJQgHFhh32/NViooGcHcUO98vTiByI1EH27d7OvZ1G6ADmkHsa74dNjDszLeiCoqWwLMe2nI4DaSUfZ8G4BeMaP9XuJHMD234Fh9p/LjKjgHA6F9sB3t8Kn0/CM9bIBnzIR1VWSaOYl/FSJ7r1P+SkMK2LES1xozTMrrgGfHUjkeDK6ywWxXA2qSRbL/jG74LGWAfGiCYMwwooskRU3N+vBmHWK6863sR9B48n921tUba8pHEO1haMp2YHGWmUQ/2Xd3vYm0tXT+MTF5axGocG0HyzXsWoT3n9R/miDr2EMG2JcU6QUnQLXNtQvqzPVW2oQDAPQw5ZgYjaBEvzEcHDBxV2KrNhQWAPqgMudvfST2x0hBWjup5tDBvXPXCFRBMULt7b0+RRC7E9JVxUUYhO+u72T5ePJkwLuZ/iEtkdiyoP+/za/6UQCnK0prxgpS2SPUw1vGYjj1obBqOinifr3HIZwA+73uG9GsENwBjE3eDQMCN9tLcNZ8RWAj7Dus85R7RhJcac=
    file:
      - "${RELEASE_PKG_FILE_DEB}"
      - "${RELEASE_PKG_FILE_TGZ}"
    skip_cleanup: true
    on:
      repo: analogdevicesinc/libsmu
      tags: true
      condition: "($TRAVIS_OS_NAME = linux)"
  - provider: releases
    api_key:
      secure: S78x4D4rzTWi3zI19dafohAplHDfyeDyzRYVz0WXf+g7WHKXa+aWPjsKyfrt8xwdkQoinzn1EwUUWjIZgpyD5gHUetdKqS5UroYOe/ZMBoT260PJ6QuZrTbg98EmDtjNrcLYHCldj2bvpoUV1gJozo32WiCND8VBttJQgHFhh32/NViooGcHcUO98vTiByI1EH27d7OvZ1G6ADmkHsa74dNjDszLeiCoqWwLMe2nI4DaSUfZ8G4BeMaP9XuJHMD234Fh9p/LjKjgHA6F9sB3t8Kn0/CM9bIBnzIR1VWSaOYl/FSJ7r1P+SkMK2LES1xozTMrrgGfHUjkeDK6ywWxXA2qSRbL/jG74LGWAfGiCYMwwooskRU3N+vBmHWK6863sR9B48n921tUba8pHEO1haMp2YHGWmUQ/2Xd3vYm0tXT+MTF5axGocG0HyzXsWoT3n9R/miDr2EMG2JcU6QUnQLXNtQvqzPVW2oQDAPQw5ZgYjaBEvzEcHDBxV2KrNhQWAPqgMudvfST2x0hBWjup5tDBvXPXCFRBMULt7b0+RRC7E9JVxUUYhO+u72T5ePJkwLuZ/iEtkdiyoP+/za/6UQCnK0prxgpS2SPUw1vGYjj1obBqOinifr3HIZwA+73uG9GsENwBjE3eDQMCN9tLcNZ8RWAj7Dus85R7RhJcac=
    file:
      - "${RELEASE_PKG_FILE_PKG}"
      - "${RELEASE_PKG_FILE_TGZ}"
    skip_cleanup: true
    on:
      repo: analogdevicesinc/libsmu
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
