matrix:
  include:
    - os: linux
      language: python
      sudo: required
      dist: trusty
    - os: osx
      osx_image: xcode61

addons:
  apt:
    packages:
      - libusb-1.0
      - libboost-all-dev

before_install:
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew update; fi

install:
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew install libusb --universal; fi
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then brew install python; fi

  # for python bindings
  - pip install --disable-pip-version-check --upgrade pip
  - pip install wheel cython

script:
  - mkdir build
  - pushd build
  - cmake -DBUILD_PYTHON=OFF ..
  - make

  # create generic binary shell-based installer/tarball
  - make package

  # build OS X installer
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then chmod +x build-osx-pkg.sh; fi
  - if [[ ${TRAVIS_OS_NAME} == osx ]]; then ./build-osx-pkg.sh; fi

  - popd

  # check python version
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  # build python bindings
  - pushd bindings/python
  - python setup.py build_ext -L ../../build/src
  - python setup.py build
  - python setup.py bdist_wheel --skip-build
