os: Visual Studio 2015
clone_depth: 1

install:
  # libusb patched for windows hotplug support
  - git clone https://github.com/analogdevicesinc/libusb.git "C:\libusb"
  # install innosetup for creating installers
  - choco install InnoSetup
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"

build_script:
  # build our own libusb version with hotplug support until upstream merges related patches
  - ps: pushd "C:\libusb"
  - git checkout hotplug
  - msbuild msvc\libusb_2015.sln /p:Platform=Win32 /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild msvc\libusb_2015.sln /p:Platform=x64 /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: popd

  - mkdir c:\projects\libsmu\32
  - cd c:\projects\libsmu\32
  - cmake -G "Visual Studio 14 2015" \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_SYSTEM_PREFIX_PATH="C:" \
    -DLIBUSB_LIBRARIES="C:\\libusb\\Win32\\Release\\dll\\libusb-1.0.lib" \
    -DLIBUSB_INCLUDE_DIRS="C:\\libusb\\libusb" \
    ..
  - cmake --build . --config Release

  - mkdir c:\projects\libsmu\64
  - cd c:\projects\libsmu\64
  - cmake -G "Visual Studio 14 2015 Win64" \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_SYSTEM_PREFIX_PATH="C:" \
    -DLIBUSB_LIBRARIES="C:\\libusb\\x64\\Release\\dll\\libusb-1.0.lib" \
    -DLIBUSB_INCLUDE_DIRS="C:\\libusb\\libusb" \
    ..
  - cmake --build . --config Release

  # create libsmu zipfile
  - mkdir c:\libsmu
  - mkdir c:\libsmu\32
  - mkdir c:\libsmu\64
  - copy ..\src\libsmu.hpp c:\libsmu
  - copy ..\src\libsmu.h c:\libsmu
  - copy ..\32\src\Release\libsmu.* c:\libsmu\32
  - copy ..\64\src\Release\libsmu.* c:\libsmu\64
  - copy ..\32\src\cli\Release\smu.exe c:\libsmu\32
  - copy ..\64\src\cli\Release\smu.exe c:\libsmu\64
  - copy "C:\\libusb\\Win32\\Release\\dll\\libusb-1.0.dll" c:\libsmu\32
  - copy "C:\\libusb\\x64\\Release\\dll\\libusb-1.0.dll" c:\libsmu\64
  - copy "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\redist\\x86\\Microsoft.VC140.CRT\\msvcp140.dll"; c:\libsmu\32
  - copy "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\redist\\x86\\Microsoft.VC140.CRT\\vcruntime140.dll"; c:\libsmu\32
  - copy "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\redist\\x64\\Microsoft.VC140.CRT\\msvcp140.dll"; c:\libsmu\64
  - copy "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\redist\\x64\\Microsoft.VC140.CRT\\vcruntime140.dll"; c:\libsmu\64
  - 7z a "c:\libsmu.zip" c:\libsmu
  - appveyor PushArtifact c:\libsmu.zip

  ## build 32 bit python bindings
  # add python dirs to PATH
  - set PATH=C:\\Python27;C:\\Python27\\Scripts;%PATH%
  # check we're using the right python version and arch
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # update pip to keep it from complaining
  - "pip install --disable-pip-version-check --user --upgrade pip"
  # wheel needs to be installed in order to build binary wheels for pysmu
  - "pip install wheel"

  # build python dist files
  - ps: pushd C:\projects\libsmu\bindings\python
  - set DISTUTILS_USE_SDK=1
  - set MSSdk=1
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC;%PATH%

  - "vcvarsall.bat x86"
  - "python setup.py build_ext --compiler=msvc -L ../../32/src/Release -I C:\\libusb\\libusb"
  - "python setup.py bdist_wheel"
  - "python setup.py bdist --format zip"
  - "python setup.py bdist --format msi"

  ## build 64 bit python bindings
  # add python dirs to PATH
  - set PATH=C:\\Python27-x64;C:\\Python27-x64\\Scripts;%PATH%
  # check we're using the right python version and arch
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # update pip to keep it from complaining
  - "pip install --disable-pip-version-check --user --upgrade pip"
  # wheel needs to be installed in order to build binary wheels for pysmu
  - "pip install wheel"

  - "vcvarsall.bat x64"
  - "python setup.py build_ext --compiler=msvc -L ../../64/src/Release -I C:\\libusb\\libusb"
  - "python setup.py bdist_wheel"
  - "python setup.py bdist --format zip"
  - "python setup.py bdist --format msi"
  - "python setup.py sdist"

  # push all dist files as artifacts
  - ps: Get-ChildItem dist/.\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  # copy python binding MSIs for installer
  # TODO: glob these file copies
  - mkdir c:\libsmu-python
  - copy dist\pysmu-0.88.win-amd64-py2.7.msi c:\libsmu-python\pysmu-amd64.msi
  - copy dist\pysmu-0.88.win32-py2.7.msi c:\libsmu-python\pysmu-win32.msi
  - ps: popd

  # create libsmu installer
  - copy C:\projects\libsmu\32\dist\libsmu.iss C:\projects\libsmu\dist\libsmu.iss
  - iscc C:\projects\libsmu\dist\libsmu.iss
  - appveyor PushArtifact C:\libsmu-setup.exe
