os: unstable

environment:
  matrix:
    - TOOLCHAIN: vs

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - ps: >-
      If ($env:Platform -Match "x86") {
        $env:GENERATOR="Visual Studio 14 2015"
        $env:LIBUSB_ARCHIVE="libusb-1.0-win-hp-i686.7z"
      } Else {
        $env:GENERATOR="Visual Studio 14 2015 Win64"
        $env:LIBUSB_ARCHIVE="libusb-1.0-win-hp-x86_64.7z"
      }

  - ps: (new-object System.Net.WebClient).Downloadfile("http://swdownloads.analog.com/cse/m1k/$env:LIBUSB_ARCHIVE", "c:\libusb.7z")
  - 7z x -y "C:\libusb.7z" -o"C:\libusb" > nul

  # wheel needs to be installed in order to build binary wheels for pysmu
  - C:\\Python27\python.exe -m pip install wheel"

  # install innosetup for creating installers
  - choco install InnoSetup
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"

build_script:
  - cmake -G $env:GENERATOR \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_SYSTEM_PREFIX_PATH="C:" \
    .
  - cmake --build . --config Release

  # build python wheel
  - cd bindings/python
  - C:\\Python27\python.exe setup.py bdist_wheel
  - appveyor PushArtifact dist/*


cache:
  - C:\mingw.7z -> appveyor.yml
