os: unstable

environment:
  matrix:
    - TOOLCHAIN: "Visual Studio 14 2015"
      LIBUSB_ARCHIVE: "libusb-1.0-win-hp-i686.7z"
    - TOOLCHAIN: "Visual Studio 14 2015 Win64"
      LIBUSB_ARCHIVE: "libusb-1.0-win-hp-x86_64.7z"

matrix:
  fast_finish: true

install:
  - appveyor DownloadFile "http://swdownloads.analog.com/cse/m1k/%LIBUSB_ARCHIVE%" -FileName "C:\libusb.7z"
  - 7z x -y "C:\libusb.7z" -o"C:\libusb" > nul

  # wheel needs to be installed in order to build binary wheels for pysmu
  - C:\\Python27\python.exe -m pip install wheel"

  # install innosetup for creating installers
  - choco install InnoSetup
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"

build_script:
  - cmake -G "%TOOLCHAIN%" \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_SYSTEM_PREFIX_PATH="C:" \
    .
  - cmake --build . --config Release

  # build python wheel
  - cd bindings/python
  - C:\\Python27\python.exe setup.py bdist_wheel
  - appveyor PushArtifact dist/*


cache:
  - C:\mingw.7z -> appveyor.yml
