os: unstable

environment:
  global:
    PYTHON: "C:\\Python27"
    DISTUTILS_USE_SDK: "1"
  matrix:
    - TOOLCHAIN: "Visual Studio 14 2015"
    - TOOLCHAIN: "Visual Studio 14 2015 Win64"

matrix:
  fast_finish: true

install:
  # libusb patched for windows hotplug support
  - git clone https://github.com/analogdevicesinc/libusb.git "C:\libusb"

  # wheel needs to be installed in order to build binary wheels for pysmu
  - "%PYTHON%\\python.exe -m pip install wheel"

  # install innosetup for creating installers
  - choco install InnoSetup
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"

build_script:
  # build our own libusb version with hotplug support until upstream merges related patches
  - ps: pushd "C:\libusb"
  - git checkout hotplug
  - msbuild msvc\libusb_2015.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: popd

  - cmake -G "%TOOLCHAIN%" \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_SYSTEM_PREFIX_PATH="C:" \
    -DLIBUSB_LIBRARIES="C:\\libusb\\Win32\\Release\\lib\\libusb-1.0.lib" \
    -DLIBUSB_INCLUDE_DIRS="C:\\libusb\\libusb" \
    .
  - cmake --build . --config Release

  # create libsmu zipfile
  - mkdir c:\libsmu
  - copy src\libsmu.hpp c:\libsmu\
  - copy src\Release\libsmu.* c:\libsmu\
  - 7z a "c:\libsmu.zip" c:\libsmu
  - appveyor PushArtifact c:\libsmu.zip

  # create libsmu installer

  # build python wheel
  - ps: pushd bindings/python
  - set DISTUTILS_USE_SDK=1
  - set MSSdk=1
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - appveyor PushArtifact dist/*
  - ps: popd

cache:
  - C:\mingw.7z -> appveyor.yml
