os: Visual Studio 2015

platform:
  - Win32
  - x64

matrix:
  fast_finish: true

install:
  - ps: >-
      If ($env:Platform -Match "Win32") {
        $env:CMAKE_GENERATOR="Visual Studio 14 2015"
        $env:PYTHON="C:\\Python27"
        $env:PYTHON_ARCH="x86"
      } Else {
        $env:CMAKE_GENERATOR="Visual Studio 14 2015 Win64"
        $env:PYTHON="C:\\Python27-x64"
        $env:PYTHON_ARCH="x64"
      }

  # libusb patched for windows hotplug support
  - git clone https://github.com/analogdevicesinc/libusb.git "C:\libusb"

  # add python dirs to PATH
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  # check we're using the right python version and arch
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # update pip to keep it from complaining
  - "pip install --disable-pip-version-check --user --upgrade pip"
  # wheel needs to be installed in order to build binary wheels for pysmu
  - "pip install wheel"

  # install innosetup for creating installers
  - choco install InnoSetup
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"

build_script:
  # build our own libusb version with hotplug support until upstream merges related patches
  - ps: pushd "C:\libusb"
  - git checkout hotplug
  - msbuild msvc\libusb_2015.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: popd

  - cmake -G "%CMAKE_GENERATOR%" \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_SYSTEM_PREFIX_PATH="C:" \
    -DLIBUSB_LIBRARIES="C:\\libusb\\%Platform%\\Release\\lib\\libusb-1.0.lib" \
    -DLIBUSB_INCLUDE_DIRS="C:\\libusb\\libusb" \
    .
  - cmake --build . --config Release

  # create libsmu zipfile
  - mkdir c:\libsmu
  - copy src\libsmu.hpp c:\libsmu
  - copy src\Release\libsmu.* c:\libsmu
  - copy src\cli\Release\smu.exe c:\libsmu
  - 7z a "c:\libsmu-%PYTHON_ARCH%.zip" c:\libsmu
  - appveyor PushArtifact c:\libsmu-%PYTHON_ARCH%.zip

  # create libsmu installer
  - iscc C:\projects\libsmu\libsmu.iss
  - appveyor PushArtifact C:\libsmu-setup.exe

  # build python wheel
  - ps: pushd bindings/python
  - set DISTUTILS_USE_SDK=1
  - set MSSdk=1
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC;%PATH%
  - "vcvarsall.bat %PYTHON_ARCH%"
  - "python setup.py build_ext --compiler=msvc -L ../../src/Release"
  - "python setup.py bdist_wheel"
  - "python setup.py bdist --format zip"
  - "python setup.py bdist --format msi"
  - ps: Get-ChildItem dist/.\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: popd
